apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deploy
  labels:
    app: baza

spec:
  template:
    metadata:
      name: postgres-deploy
      labels:
        bb: baza

    spec: 
      containers:
        - name: postgres-baza
          image: postgres:alpine
          ports:
            - containerPort: 5432 
          # volumeMounts:
          # - mountPath: /postgres-data:/var/lib/postgresql/data
          #   name: pg-volume
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-claim
      # volumes:
      # - name: pg-volume
      #   hostPath: 
      #     path: /tmp/vols/pgdata
      #     type: Directory
      volumes:
      - name: postgres-pv-claim
        persistentVolumeClaim:
          claimName: postgres-pv-claim
           
  replicas: 1
  selector:
    matchLabels:
      bb: baza
