apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
 containers:
 - name: first-pod
   image: nginx:alpine
   ports:
   - containerPort: 80
   command: ["wget"]
   args: ["localhost:80"]